### PR TITLE
Fix is/is not operators applied to None result

### LINKED ISSUE #73: UnboundLocalError: local variable 'ret' referenced before assignment
Hi!

It's my first time using ObjectPath, and I'm getting this error:
```
Traceback (most recent call last):
  File "script.py", line 19, in <module>
    res = tree.execute('$.issues[@.changelog.histories[@.items[0].toString is "Done"]]')
  File "C:\Users\cmmartins\AppData\Local\Programs\Python\Python37-32\lib\site-packages\objectpath\core\interpreter.py", line 608, in execute
    ret=exe(tree)
  File "C:\Users\cmmartins\AppData\Local\Programs\Python\Python37-32\lib\site-packages\objectpath\core\interpreter.py", line 328, in exe
    nodeList_append(exe((selector[0],exe(selector[1]),exe(selector[2]))))
  File "C:\Users\cmmartins\AppData\Local\Programs\Python\Python37-32\lib\site-packages\objectpath\core\interpreter.py", line 234, in exe
    return ret
UnboundLocalError: local variable 'ret' referenced before assignment
``` 

I don't know if my query is wrong (toString is a property, maybe this is the problem?) but the error is not being treated. I saw this issue in another repo (https://github.com/miguelgrinberg/python-socketio/issues/85), maybe this guy solution helps you.

Thank you!

### PR DESCRIPTION
**Pull request by yohanboniface**
This should fix #73 

Side note:  a run of flake8/black on the files should help new contributors :)

### CODE REVIEW

**Comment by adriank** [comment]
Thanks for the PR, but I had to do it a little bit differently.

**Comment by yohanboniface** [comment]
> Thanks for the PR, but I had to do it a little bit differently.

OK, thanks!

> I added the yapf support.

Seems to me there are still mixed spaces and tab, and other pep 8 infrigements :(
Honestly, if you are not confident with pep8, just use [black](https://pypi.org/project/black/), it will make your life easier, and the files much more welcoming for new contributors. :)

Also, are you planning to push a new release on pypi? :)

**Comment by adriank** [comment]
PEP8 is very opinionated and the community wasn't so religious about it in
2010 when I wrote ObjectPath. The library is not trivial and PEP8 is just
not enough to make the code readable.

I uploaded ObjectPath 0.6 to PyPi just an hour ago.

Greetings,
Adrian Kalbarczyk

http://kalbarczyk.co

ᐧ

**Comment by yohanboniface** [comment]
> PEP8 is just not enough to make the code readable.

Still a good path forward :)

> I uploaded ObjectPath 0.6 to PyPi just an hour ago.

Thanks! :)

**Comment by adriank** [comment]
symbol_table = {}
token = nextToken = None
# TODO optimization ('-',1) -> -1
# TODO optimization operators should be numbers

TRUE = ["true", "t"]
FALSE = ["false", "f"]
NONE = ["none", "null", "n", "nil"]

How would you make this code compatible with C0103? If you'd use upper case
for the symbol_table and token you would misinform other coders. They'd
expect these variables to be constants while one is a container for
variables and the other two are variables.

C0123 R0911 R0912 made code slow back in 2010 and I believe this is the
case also right now.

W0703 makes writing ObjectPath in Python impossible.

etc.

Greetings,
Adrian Kalbarczyk

http://kalbarczyk.co

ᐧ

**Pull request closed without merging**
