### PR TITLE
Include link to SakStig

### PR DESCRIPTION
**Pull request by redhog**
* Made a new page listing all implementations
* Added a link to SakStig in the list of implementations

### CODE REVIEW

**Comment by redhog** [comment]
ping @adriank

**Comment by adriank** [comment]
Egil,

Please add installation guide on SakStig page. If I will be able to install SakStig and it passes all ObjectPath tests I will merge this PR.

Thanks,
Adrian

**Comment by redhog** [comment]
The page now contains an installation guide (it's as simple as pip install sakstig).

Below is how you can run your tests (from latest ObjectPath master) on sakstig. It uses a wrapper script to convince your tests to use the sakstig interpreter instead of the ObjectPath one, as well as a tiny hack to make your tests work with Python3 (a renamed method). Note: This all requires Python 3.... As you can see all tests pass (as of 2019-11-18):

    (env) redhog@glittertind:~/sakstig $ python setup.py install
    
    (env) redhog@glittertind:~/sakstig $ git clone git@github.com:adriank/ObjectPath.git
    Cloning into 'ObjectPath'...

    (env) redhog@glittertind:~/sakstig$ env/bin/nose2 -v -s tests/ test_ObjectPath.ObjectPath
    test_arithm_add (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_arithm_div (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_arithm_group (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_arithm_mod (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_arithm_mul (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_arithm_parentheses (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_arithm_sub (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_arrays (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_builtin_arithmetic (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_builtin_arrays (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_builtin_casting (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_builtin_string (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_builtin_time (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_builtin_type (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_comparison_gt (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_comparison_is (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_comparison_isnot (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_comparison_lt (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_comparison_regex (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_complex (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_concatenation (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_localize (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_logic_and (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_logic_negatives (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_logic_not (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_logic_or (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_membership_in (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_membership_notin (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_misc (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_objects (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_optimizations (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_selector_with_empty_result (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_simple_types (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok

    ----------------------------------------------------------------------
    Ran 33 tests in 0.176s

    OK

**Comment by redhog** [comment]
Hi!

There is a simple installation instruction in the README (pip install :)

I have made sure all tests pass (as of 2019-11-19) - I have provided a [wrapper script](https://github.com/innovationgarage/sakstig/blob/master/tests/test_ObjectPath.py) that runs the tests out of the current master of an ObjectPath repo clone, but monkeypatched to use the sakstig query engine instead of the ObjectPath one.

Note that there's a "compatibility" flag that if set to False will make sakstig deviate from some ObjectPath semantics in some corner cases. These are documented on the homepage. If set to True (the default), sakstig should not deviate ever.

    (env) redhog@glittertind:~/sakstig $ python setup.py develop
    ...
    Finished processing dependencies for sakstig==0.1.6
    (env) redhog@glittertind:~/sakstig $ git clone git@github.com:adriank/ObjectPath.git
    Cloning into 'ObjectPath'...
    ...
    (env) redhog@glittertind:~/sakstig $ env/bin/nose2 -v -s tests/
    test_arithm_add (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_arithm_div (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_arithm_group (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_arithm_mod (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_arithm_mul (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_arithm_parentheses (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_arithm_sub (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_arrays (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_builtin_arithmetic (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_builtin_arrays (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_builtin_casting (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_builtin_string (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_builtin_time (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_builtin_type (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_comparison_gt (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_comparison_is (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_comparison_isnot (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_comparison_lt (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_comparison_regex (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_complex (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_concatenation (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_localize (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_logic_and (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_logic_negatives (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_logic_not (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_logic_or (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_membership_in (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_membership_notin (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_misc (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_objects (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_optimizations (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_selector_with_empty_result (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_simple_types (ObjectPath.tests.test_ObjectPath.ObjectPath) ... ok
    test_complex_paths (ObjectPath.tests.test_ObjectPath.ObjectPath_Paths) ... ok
    test_object_list (ObjectPath.tests.test_ObjectPath.ObjectPath_Paths) ... ok
    test_selectors (ObjectPath.tests.test_ObjectPath.ObjectPath_Paths) ... ok
    test_simple_paths (ObjectPath.tests.test_ObjectPath.ObjectPath_Paths) ... ok
    test_arithm_add (tests.test_SakStig.ObjectPath) ... ok
    test_arithm_div (tests.test_SakStig.ObjectPath) ... ok
    test_arithm_group (tests.test_SakStig.ObjectPath) ... ok
    test_arithm_mod (tests.test_SakStig.ObjectPath) ... ok
    test_arithm_mul (tests.test_SakStig.ObjectPath) ... ok
    test_arithm_parentheses (tests.test_SakStig.ObjectPath) ... ok
    test_arithm_sub (tests.test_SakStig.ObjectPath) ... ok
    test_arrays (tests.test_SakStig.ObjectPath) ... ok
    test_builtin_arithmetic (tests.test_SakStig.ObjectPath) ... ok
    test_builtin_arrays (tests.test_SakStig.ObjectPath) ... ok
    test_builtin_casting (tests.test_SakStig.ObjectPath) ... ok
    test_builtin_string (tests.test_SakStig.ObjectPath) ... ok
    test_builtin_time (tests.test_SakStig.ObjectPath) ... ok
    test_builtin_type (tests.test_SakStig.ObjectPath) ... ok
    test_comparison_gt (tests.test_SakStig.ObjectPath) ... ok
    test_comparison_is (tests.test_SakStig.ObjectPath) ... ok
    test_comparison_isnot (tests.test_SakStig.ObjectPath) ... ok
    test_comparison_lt (tests.test_SakStig.ObjectPath) ... ok
    test_comparison_regex (tests.test_SakStig.ObjectPath) ... ok
    test_complex (tests.test_SakStig.ObjectPath) ... ok
    test_concatenation (tests.test_SakStig.ObjectPath) ... ok
    test_localize (tests.test_SakStig.ObjectPath) ... ok
    test_logic_and (tests.test_SakStig.ObjectPath) ... ok
    test_logic_negatives (tests.test_SakStig.ObjectPath) ... ok
    test_logic_not (tests.test_SakStig.ObjectPath) ... ok
    test_logic_or (tests.test_SakStig.ObjectPath) ... ok
    test_membership_in (tests.test_SakStig.ObjectPath) ... ok
    test_membership_notin (tests.test_SakStig.ObjectPath) ... ok
    test_misc (tests.test_SakStig.ObjectPath) ... ok
    test_objects (tests.test_SakStig.ObjectPath) ... ok
    test_optimizations (tests.test_SakStig.ObjectPath) ... ok
    test_simple_types (tests.test_SakStig.ObjectPath) ... ok
    test_complex_paths (tests.test_SakStig.ObjectPath_Paths) ... ok
    test_selectors (tests.test_SakStig.ObjectPath_Paths) ... ok
    test_simple_paths (tests.test_SakStig.ObjectPath_Paths) ... ok

    ----------------------------------------------------------------------
    Ran 72 tests in 0.350s

    OK

    (env) redhog@glittertind:~/sakstig $

**Comment by redhog** [comment]
Just for completeness, here is the commit ID of the version of ObjectPath I used for the test suite:

https://github.com/adriank/ObjectPath/commit/f240821fa197ef5cd04f189c776ae356813abb2b

**Comment by adriank** [comment]
Nice, you solved many bugs that I didn't have time to fix in recent years with Sakstig. Maybe we should do some call to discuss what would benefit the project the best. Should we merge those projects making my 10-year-old implementation just for historical purposes and making Sakstig the default or keeping projects separate etc. 

Your change on the site is not visible enough in my opinion. We need to think about how to expose Sakstig a little bit better.

**Comment by redhog** [comment]
Cool! Sure. redhog_org on skype, redhog.org@gmail.com on google hangout. When would you have time? I'm based in Norway, and can do calls during the week, either during the workday or in the evening, including today...

**Comment by redhog** [comment]
ping

**Pull request closed without merging**
